from django.db import models

# So basically, here we are going to create our database stuff...
# But instead of using SQL language for that, we are going to work with...
# Classes in Python to literally model our database.

# So let's build a generic database, with simple info, such as name, age...

class Member(models.Model):
#   So that's the basic structure to create our database info...
#   So, to get more information about which models we can use, you can access...
#   The Django Documentation, searching for 'Modules'.

#   Defining the columns of our table 'Member'...      
    fname = models.CharField(max_length=50)
    lname = models.CharField(max_length=100)
    email = models.EmailField(max_length=200)
    passwd = models.CharField(max_length=50)
    age = models.IntegerField()
#   By default, we will have a Primary Key id, that comes along with every table.

#   This function will give a name to our object...
    def __str__(self) -> str:
        return self.fname + ' ' + self.lname

# So that's the first step of our three step process...
# The second step is to make these migrations, and then migrate them. 

# Write on terminal 'python manage.py makemigrations'...
# This will even create a migrations folder in our app, anyway, after that...
# Write 'python manage.py migrate', and it's done. 